version: '3.1'

services:
  
# Optional MySQL db service.
#  db:
#    image: mysql
#    container_name: mysql-db
#    restart: on-failure:10
#    env_file: ".env"
#    ports:
#      - 3306:3306/tcp
#    volumes:
#      - ./mysql_data:/var/lib/mysql

  themepark-server:
    image: node:20
    container_name: themepark-server
    restart: on-failure:10
    env_file: "./.env"
    volumes:
      - ./server/build:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && node main.js"
    ports:
      - 8080:8080/tcp

  themepark-website:
    image: nginx:latest
    container_name: themepark-website
    restart: on-failure:10
    volumes:
      - ./build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80/tcp
