version: '3.1'

services:
  
  themepark-website:
    image: nginx:latest
    container_name: themepark-website
    restart: on-failure:10
    volumes:
      - ./build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80/tcp
