version: '3.1'

services:

  themepark-server:
    image: node:20 # latest LTS version of node
    container_name: themepark-server
    restart: on-failure:10
    env_file: "../.env"
    volumes:
      - ./server_root:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "npm install && node main.js"
    ports:
      - 8080:8080/tcp