version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    env_file: "../.env"
    ports:
      - 3306:3306/tcp
    volumes:
      - ./mysql_data:/var/lib/mysql
