version: '3.1'

services:
  
  themepark-website:
    image: nginx:latest
    container_name: themepark-website
    restart: on-failure:10
    volumes:
      - ./build:/var/www/http
    ports:
      - 80:80/tcp
      - 443:443/tcp